import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./component/Sidebar";
import Navbar from "./component/navbar/Navbar";
import { UserProvider } from "@/context/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fauget",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>

          <div className="drawer lg:drawer-open">
            <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content bg-[#191919] px-6">

              <Navbar />
              {children}

            </div>
            <div className="drawer-side">
              <label htmlFor="my-drawer-2" aria-label="close sidebar" className="drawer-overlay"></label>
              <Sidebar></Sidebar>

            </div>
          </div>



        </body>
      </html>
    </UserProvider>
  );
}
